name: POE cybersecurity awareness CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore "POE cybersecurity awareness.sln"

      - name: Check Code Formatting
        run: dotnet format --verify-no-changes "POE cybersecurity awareness.sln" || exit 1

      - name: Build Project
        run: msbuild "POE cybersecurity awareness.sln" /p:Configuration=Release
